### ISSUE TITLE
Hands not tracking using Vive.

### ISSUE THREAD

**Issue by HiroTsuguS** [Raicuparta/NomaiVR#59]
When I get in game the hands aren't tracking to my wands.

**Comment by Raicuparta** [comment]
Hi @HiroTsuguS 

Are you able to control anything in the game using the inputs on your Vive wands? For instance, were you able to navigate the main menu using the trackpads? Or did you start the game using a normal controller / keyboard?

**Comment by HiroTsuguS** [comment]
Yes, the buttons on the wands work, but the hands are just frozen in the floor and don't match the wands.

**Comment by Raicuparta** [comment]
@HiroTsuguS Looks like I didn't map the motion poses to the controllers. I have just released a new version (0.81). Please let me know if it's fixed for you.

Hopefully they mappings I uploaded will replace your custom SteamVR input mappings (if you have any). If it still doesn't work, please go to SteamVR Settings menu (by clicking the burger menu on the top left of that tiny SteamVR window, and then Settings), and while the game is open go to Controllers > Show Old Binding UI (for me always seems easier to go through here). If you have a custom mapping you should delete it, so that the game uses the one I defined.

**Comment by HiroTsuguS** [comment]
It works now, thank you.
