### ISSUE TITLE
UI elements are obstructed when below the currents of Giants Deep

### ISSUE THREAD

**Issue by SpikeEscape** [Raicuparta/NomaiVR#65]
After taking the backwards whirlpool to get to the core of giants deep I noticed that some of the custom UI (the jet pack thruster display specifically) would be drawn underneath the deep water effect,

rendering them invisible unless I turned my hand in a way that the UI would be in front of my vr hand instead of infront of the water. This is what lead me to believe this is a layering/depth issue with the underwater effects rendering in front of the UI.

**Comment by Raicuparta** [comment]
Thanks for the report. This will probably be "fixed" along with #11 by just disabling the underwater effects altogether, because they don't feel very nice in VR. Hopefully it doesn't ruin the atmosphere too much.

**Comment by Raicuparta** [comment]
@SpikeEscape what version did you test? Was it 0.6 or a later one? In 0.7 I increased the gap between the camera and the helmet, so this would make things slightly better.

I just tested it myself and it seems fine? The rain effect is exactly where the helmet visor is, which makes sense. Of course you'll see double because you're looking through the visor to focus on something far away. But that's what would happen in real life too.

If you have seen the effect in 0.7+, let me know if you think this is something that bothers you. I can make a note to make the effect toggleable.

**Comment by Raicuparta** [comment]
Looks like I was wrong, it's not related to the underwater distortion effect! Very good catch, I'll see what I can do to fix it.

**Comment by Raicuparta** [comment]
Seems to be a problem with the material shaders used by these HUD elements. I'll need to find different shaders for each element.

The mini-map sphere uses the "GeometryTexture" shader, for instance. Changing it to the Standard shader fixes the bug, but makes the minimap look weird. Might be tricky to find something that looks OK for all the elements.
