### ISSUE TITLE
Dialogue boxes rotate with the NPC, and so can appear backwards and behind them

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#99]
This issue is most noticeable for me with the initial Hornfels dialogue in the observatory, as they rotate 180 degrees to speak with you. The dialogue box first appears where it should, in front of the player, but then rotates around Hornfels as they turn, until it appears on the opposite side of them.

**Comment by Raicuparta** [comment]
@stephaje Can you take a look at this?

**Comment by Raicuparta** [comment]
@Z5aI69A61 any clue of other scenarios where this happens? Hard to test if we need to make a new save every time...

**Comment by stephaje** [comment]
So looks like we'll need to utilize Dialog.Update() after all. We could either check to see if the _attentionPoint has changed, changed position, or changed rotation, and update the dialog canvas, or just update it every frame regardless. The latter is less bug prone and since most things in the game should be paused during dialog, I don't think we need to worry about efficiency.

If anyone can think of points in dialog where the attention shifts from one object to another, it would be a good thing to try out while testing.

I can take a look in 8h or so.

**Comment by Raicuparta** [comment]
@stephaje I think the fix is simpler than that. Instead of parenting the dialog canvas to the attention point transform, just set the world position of the dialog canvas to the position of the attention point. Since you only set it up at the start of a conversation, it won't rotate any more when the character rotates.

**Comment by stephaje** [comment]
@Raicuparta unless there's any instances of the attention point moving between two objects or it moving around the room (e.x. an NPC walking). I can't think of any instances at the moment, but maybe better safe than sorry?

**Comment by Raicuparta** [comment]
@stephaje The only situation I remember of moving during dialogue was in Giant's Deep while talking to the explorer dude and the island is thrown to space, but in that case the dialog just closed itself. So I don't think you need to worry about that.

**Comment by Raicuparta** [comment]
@stephaje From user reports looks like there might be a small chance of the user moving during conversations, but I'd say that's more of a bug with the original game than a bug with this feature. Do whatever you think is best with this information, if you prefer to do it on Update, that's fine too :)
